#logging:
#  level:
#    root: debug

server:
  port: 8087
  servlet:
    context-path: '/cart'

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=cart
      username: cart
      password: qwerty123
    rabbitmq:
      host: localhost
      port: 5672
      username: rabbit
      password: rabbit
    redis:
      host: localhost
      port: 6379

app.basePath: /cart
users.url: http://localhost:8081/users